### ISSUE TITLE
Builds are failing for the last few weeks

### ISSUE THREAD

**Issue by kylechase** [jack-broadway/vyos-modular#14]
Trying to build a new base iso, 1.3.5, equuleus.  Circinus and Sagitta builds also fail.  Please let me know if you need anything else.

The command
```
vyos-modular build_iso -b 1.3.5 -r equuleus
```

Output log attached
[terminal-log.txt](https://github.com/jack-broadway/vyos-modular/files/14876158/terminal-log.txt)

**Comment by schilling-ryan** [comment]
Pretty sure this is not just related to this project but VyOS in general. VyOS took down their own repos which were used (per their own instructions) to build ISOs from scratch and they decided they didn't like that they weren't getting enough stars on Github so the best course of action was to break builds like this.

https://www.reddit.com/r/vyos/s/cxkGJ0ec9t

https://blog.vyos.io/community-contributors-userbase-and-lts-builds

**Comment by jack-broadway** [comment]
We'll that's a disappointing turn of events :/ vyos-modular already takes in pre-built isos so at least that will still work if you access to LTS isos, or older built bases

**Comment by jack-broadway** [comment]
Looking at that output, that specific bug is a bug in the vyos build unfortunately, there are now multiple kernel versions available but their build script only expects a single
